// verify-cask.mjs — fail CI when the committed Homebrew cask doesn't match its published release.
//
// `npm run version:set` (scripts/bump-version.mjs) bumps the cask's `version` field but does NOT
// touch `sha256` — the correct hash only exists after that version's .dmg is built AND published
// (the .dmg is ad-hoc signed per build, so there is no byte reproducibility to precompute from).
// That leaves a window where the cask reads "version=NEW, sha256=OLD" until someone runs
// `update-cask.mjs` post-publish and commits — hit for real at v0.4.0 (Issue #287).
//
// Where this runs (and deliberately does NOT): a paths-filtered workflow that fires only on changes
// under packaging/homebrew/** (.github/workflows/verify-cask.yml). It is NOT wired into release.yml:
// at tag-build time the cask's sha256 is structurally the PREVIOUS cycle's value (the new dmg's hash
// cannot exist yet), so a release-time comparison would false-red every healthy release (PR #310).
// The moment the cask must be right is "when the cask lands on main" — which is what the paths
// filter checks. A cask whose version has no published release yet fails too (never-silent): that IS
// the stale window this guard exists for; it clears once `update-cask.mjs` is run post-publish.
//
//   node scripts/verify-cask.mjs
//
// Reads the cask's own `version` field, fetches that version's published SHA256SUMS release asset,
// and compares via `caskMatchesSums` (shared with update-cask.mjs — the write side; R8: one sha
// reading/matching implementation, not two). Failures set `process.exitCode` and unwind (same
// Windows-safe convention as update-cask.mjs — no abrupt process.exit() racing an open fetch handle).
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { caskMatchesSums, parseCaskVersion, REPO } from "./update-cask.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const caskPath = join(here, "..", "packaging", "homebrew", "Casks", "slidecraft.rb");

/** The published SHA256SUMS asset for a version (generated by release.yml's checksums job). */
function sumsUrl(version) {
  return `https://github.com/${REPO}/releases/download/v${version}/SHA256SUMS`;
}

/**
 * The whole check minus I/O bindings: reads the version from `caskText`, fetches that version's
 * published SHA256SUMS via `fetchFn` (injectable so tests mock the network), compares. Returns
 * { ok, reason } and never throws on the expected failure paths — every failure is a reportable
 * reason, so the CLI below can stay never-silent.
 */
export async function verifyCask(caskText, fetchFn = fetch) {
  const version = parseCaskVersion(caskText);
  if (!version) return { ok: false, reason: 'cask has no version "…" line — check the template' };
  const url = sumsUrl(version);
  let res;
  try {
    res = await fetchFn(url);
  } catch (e) {
    return { ok: false, reason: `fetch failed for ${url}: ${e}` };
  }
  if (!res.ok) {
    return {
      ok: false,
      reason:
        `download failed (${res.status} ${res.statusText}) for ${url} — is v${version} published? ` +
        `A cask must only carry a version whose release (and SHA256SUMS) already exists; run ` +
        `\`node scripts/update-cask.mjs ${version}\` after publishing.`,
    };
  }
  if (!caskMatchesSums(caskText, await res.text(), version)) {
    return {
      ok: false,
      reason:
        `cask sha256 does NOT match the published SHA256SUMS for v${version} (stale sha — the #287 ` +
        `window). Run \`node scripts/verify-cask.mjs\` locally after \`node scripts/update-cask.mjs ${version}\` and commit.`,
    };
  }
  return { ok: true, reason: `cask sha256 matches the published SHA256SUMS for v${version}` };
}

async function main() {
  const { ok, reason } = await verifyCask(readFileSync(caskPath, "utf8"));
  if (!ok) {
    console.error(`verify-cask: ${reason}`);
    process.exitCode = 1;
    return;
  }
  console.log(`✓ verify-cask: ${reason}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
