import { useState, useCallback, useRef } from "react";
import yaml from "js-yaml";
import Editor from "./components/Editor";
import Preview from "./components/Preview";
import SlidePreview from "./components/SlidePreview";
import Toolbar from "./components/Toolbar";
import ThemePicker from "./components/ThemePicker";
import StatusBar from "./components/StatusBar";
import { DiagramSpecSchema, validateDiagramSpec, type DiagramSpec } from "./engine/schema";
import { renderToBuffer } from "./engine/pptx-writer";
import { midnightExecutive } from "./engine/theme";
import { parseMd } from "./engine/md-parser";
import { loadTemplate, type TemplateData } from "./engine/template-loader";
import { generatePptx } from "./engine/placeholder-filler";
import type { DeckIR } from "./engine/slide-schema";
import { readFileFromInput, downloadBlob } from "./ipc/commands";

type AppMode = "diagram" | "markdown";

const SAMPLE_YAML = `type: flowchart
direction: TB
title: API認証フロー

classDefs:
  process:
    fill: "#1E2761"
    border: "#3B82F6"
    font_color: "#FFFFFF"
  decision:
    fill: "#F59E0B"
    font_color: "#1E293B"
    font_size: 10
  terminal:
    fill: "#3B82F6"

nodes:
  - id: start
    label: 開始
    shape: rounded_rect
    class: terminal
  - id: proc1
    label: リクエスト受付
    class: process
  - id: auth
    label: 認証OK？
    shape: diamond
    class: decision
  - id: ok
    label: データ処理
    class: process
  - id: ng
    label: エラー返却
    class: process
  - id: end
    label: 終了
    shape: rounded_rect
    class: terminal

edges:
  - from: start
    to: proc1
  - from: proc1
    to: auth
  - from: auth
    to: ok
    label: "Yes"
  - from: auth
    to: ng
    label: "No"
  - from: ok
    to: end
  - from: ng
    to: end
`;

const SAMPLE_MD = `<!-- slide: Title.1Title.Single -->
# SlideCraft デモ
## Markdown → PPTX 変換

Category: DEMO
Date: 2026-03-31
Footer: Generated by SlideCraft

---

# 本日のアジェンダ
> Today's Agenda

- Markdown → PPTX パイプラインの紹介
- テンプレートシステムの仕組み
- WYSIWYG プレビューのデモ
- 今後のロードマップ

---

<!-- slide: Column.2Body.Equal -->
# 比較: 従来 vs SlideCraft
> Traditional vs SlideCraft

<!-- col -->
**従来の方法**

- PowerPoint を手動で編集
- テンプレート適用が面倒
- LLM の出力を手作業でコピー

<!-- col -->
**SlideCraft**

- Markdown で執筆（LLM 対応）
- テンプレート自動適用
- WYSIWYG プレビューで確認

---

<!-- slide: Closing.1Message.Single -->
# ありがとうございました
## Thank You

Date: お問い合わせ: slidecraft@example.com
Footer: SlideCraft v2
`;

export default function App() {
  const [mode, setMode] = useState<AppMode>("markdown");
  const [yamlText, setYamlText] = useState(SAMPLE_YAML);
  const [mdText, setMdText] = useState(SAMPLE_MD);
  const [spec, setSpec] = useState<DiagramSpec | null>(null);
  const [deck, setDeck] = useState<DeckIR | null>(null);
  const [templateData, setTemplateData] = useState<TemplateData | null>(null);
  const [parseError, setParseError] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [themeName, setThemeName] = useState("midnight_executive");
  const [filePath, setFilePath] = useState<string | null>(null);
  const [activeSlide, setActiveSlide] = useState(0);
  const [templateName, setTemplateName] = useState("Midnight Executive");
  const fileInputRef = useRef<HTMLInputElement>(null);
  const templateInputRef = useRef<HTMLInputElement>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // ── Diagram mode: parse YAML ──
  const parseYaml = useCallback((text: string) => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      try {
        if (!text.trim()) {
          setSpec(null);
          setParseError(null);
          return;
        }
        const data = yaml.load(text);
        if (!data || typeof data !== "object") {
          setParseError("YAML must produce an object");
          setSpec(null);
          return;
        }
        const result = DiagramSpecSchema.safeParse(data);
        if (!result.success) {
          setParseError(result.error.issues.map((i: { message: string }) => i.message).join("\n"));
          setSpec(null);
          return;
        }
        const errors = validateDiagramSpec(result.data);
        if (errors.length > 0) {
          setParseError(errors.map((e) => e.message).join("\n"));
          setSpec(null);
          return;
        }
        setSpec(result.data);
        setParseError(null);
      } catch (e) {
        setParseError(e instanceof Error ? e.message : String(e));
        setSpec(null);
      }
    }, 300);
  }, []);

  // ── Markdown mode: parse MD ──
  const parseMdText = useCallback((text: string) => {
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      try {
        if (!text.trim()) {
          setDeck(null);
          setParseError(null);
          return;
        }
        const parsed = parseMd(text);
        setDeck(parsed);
        setParseError(null);
      } catch (e) {
        setParseError(e instanceof Error ? e.message : String(e));
        setDeck(null);
      }
    }, 300);
  }, []);

  // ── Editor change handlers ──
  const handleEditorChange = useCallback(
    (value: string) => {
      if (mode === "diagram") {
        setYamlText(value);
        parseYaml(value);
      } else {
        setMdText(value);
        parseMdText(value);
      }
    },
    [mode, parseYaml, parseMdText],
  );

  // Initial parse (no debounce) + template load
  useState(() => {
    // Parse both immediately without debounce
    try {
      const data = yaml.load(SAMPLE_YAML);
      if (data && typeof data === "object") {
        const result = DiagramSpecSchema.safeParse(data);
        if (result.success) setSpec(result.data);
      }
    } catch { /* ignore */ }
    try {
      setDeck(parseMd(SAMPLE_MD));
    } catch { /* ignore */ }
    // Load template for preview
    fetch("/templates/slide/Midnight_Executive_30_TemplateOnly.pptx")
      .then((r) => r.arrayBuffer())
      .then((buf) => loadTemplate(buf))
      .then(setTemplateData)
      .catch(() => {});
  });

  // Load custom template
  const handleLoadTemplate = useCallback(() => {
    templateInputRef.current?.click();
  }, []);

  const handleTemplateSelected = useCallback(
    async (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (!file) return;
      try {
        const buf = await file.arrayBuffer();
        const tpl = await loadTemplate(buf);
        setTemplateData(tpl);
        setTemplateName(file.name.replace(/\.pptx$/i, ""));
      } catch (err) {
        setParseError(`Template load failed: ${err instanceof Error ? err.message : String(err)}`);
      }
      e.target.value = "";
    },
    [],
  );

  // Open file
  const handleOpen = useCallback(() => {
    fileInputRef.current?.click();
  }, []);

  const handleFileSelected = useCallback(
    async (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (!file) return;

      const text = await readFileFromInput(file);
      if (mode === "diagram") {
        setYamlText(text);
        parseYaml(text);
      } else {
        setMdText(text);
        parseMdText(text);
      }
      setFilePath(file.name);
      e.target.value = "";
    },
    [mode, parseYaml, parseMdText],
  );

  // Save
  const handleSave = useCallback(() => {
    const text = mode === "diagram" ? yamlText : mdText;
    const mimeType = mode === "diagram" ? "text/yaml" : "text/markdown";
    const ext = mode === "diagram" ? ".yaml" : ".md";
    const blob = new Blob([text], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filePath ?? `slidecraft${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  }, [mode, yamlText, mdText, filePath]);

  // Generate PPTX
  const handleGenerate = useCallback(async () => {
    setGenerating(true);
    try {
      if (mode === "diagram") {
        if (!spec) return;
        const theme = midnightExecutive();
        const buffer = await renderToBuffer(spec, { theme });
        const filename = spec.title
          ? `${spec.title.replace(/[^\w\s-]/g, "").trim()}.pptx`
          : "diagram_output.pptx";
        downloadBlob(buffer, filename);
      } else {
        if (!deck || !templateData) return;
        const buffer = await generatePptx(deck, templateData);
        downloadBlob(buffer as unknown as Uint8Array, "slides_output.pptx");
      }
    } catch (e) {
      setParseError(`PPTX generation failed: ${e instanceof Error ? e.message : String(e)}`);
    } finally {
      setGenerating(false);
    }
  }, [mode, spec, deck, templateData]);

  const hasContent = mode === "diagram" ? spec !== null : (deck !== null && templateData !== null);
  const editorValue = mode === "diagram" ? yamlText : mdText;
  const editorLang = mode === "diagram" ? "yaml" : "yaml"; // CodeMirror: markdown mode TBD

  return (
    <>
      <input
        ref={fileInputRef}
        type="file"
        accept={mode === "diagram" ? ".yaml,.yml,.json" : ".md,.markdown,.txt"}
        className="hidden"
        onChange={handleFileSelected}
      />
      <input
        ref={templateInputRef}
        type="file"
        accept=".pptx"
        className="hidden"
        onChange={handleTemplateSelected}
      />

      <div className="flex items-center">
        <Toolbar
          onOpen={handleOpen}
          onSave={handleSave}
          onGenerate={handleGenerate}
          onLoadTemplate={handleLoadTemplate}
          generating={generating}
          hasSpec={hasContent}
          templateName={templateName}
          mode={mode}
        />
        <div className="flex items-center gap-2 px-3 py-2 bg-[#1E2761] border-b border-[#3B82F6]/30">
          {/* Mode toggle */}
          <div className="flex rounded overflow-hidden border border-[#3B82F6]/40 text-xs">
            <button
              onClick={() => { setMode("diagram"); parseYaml(yamlText); }}
              className={`px-3 py-1 transition-colors ${
                mode === "diagram"
                  ? "bg-[#3B82F6] text-white"
                  : "bg-[#1E2761] text-gray-400 hover:text-white"
              }`}
            >
              Diagram
            </button>
            <button
              onClick={() => { setMode("markdown"); parseMdText(mdText); }}
              className={`px-3 py-1 transition-colors ${
                mode === "markdown"
                  ? "bg-[#3B82F6] text-white"
                  : "bg-[#1E2761] text-gray-400 hover:text-white"
              }`}
            >
              Markdown
            </button>
          </div>
          {mode === "diagram" && (
            <ThemePicker currentTheme={themeName} onThemeChange={setThemeName} />
          )}
        </div>
      </div>

      <div className="flex-1 flex min-h-0">
        <div className="w-1/2 border-r border-[#2D3A6E] flex flex-col min-h-0">
          <div className="px-3 py-1 bg-[#141B41] text-xs text-gray-400 border-b border-[#2D3A6E]">
            {mode === "diagram" ? "YAML Editor" : "Markdown Editor"}
          </div>
          <div className="flex-1 min-h-0">
            <Editor value={editorValue} onChange={handleEditorChange} language={editorLang} />
          </div>
        </div>

        <div className="w-1/2 flex flex-col min-h-0 bg-[#0f1117]">
          <div className="px-3 py-1 bg-[#141B41] text-xs text-gray-400 border-b border-[#2D3A6E]">
            {mode === "diagram" ? "Mermaid Preview" : "Slide Preview"}
          </div>
          <div className="flex-1 min-h-0">
            {mode === "diagram" ? (
              <Preview spec={spec} error={parseError} />
            ) : (
              <SlidePreview
                deck={deck}
                template={templateData}
                error={parseError}
                activeSlide={activeSlide}
                onSlideClick={setActiveSlide}
              />
            )}
          </div>
        </div>
      </div>

      <StatusBar spec={spec} error={parseError} filePath={filePath} />
    </>
  );
}
